import { ArrowRight, Cloud, CloudDrizzle, CloudSun, Droplets, RefreshCw, Sun, ThermometerSun, Wind } from 'lucide-react';
import { SectionHeading, SourceNote, StatusBadge, WhyButton } from '../components/Shared';
import { timeAgo } from '../lib/model';
import type { FarmSnapshot, FieldData, View } from '../lib/types';

export function Weather({snapshot,selected,navigate,selectField,refresh,why}: {snapshot:FarmSnapshot;selected:FieldData;navigate:(v:View)=>void;selectField:(id:string)=>void;refresh:()=>void;
  why:(id:string,kind:'irrigation')=>void}) {
  const w=snapshot.weather;
  return <div className="page-stack"><div className="page-intro"><div><p className="eyebrow">WEATHER INTELLIGENCE / {snapshot.farm.district.toUpperCase()}</p><h1>Plan with the sky.</h1><p>Weather matters most when it's connected to your soil and crop.</p></div><button className="button button--secondary" onClick={refresh}><RefreshCw size={16}/> Check for updates</button></div>
    <div className="weather-top"><section className="weather-current"><div className="weather-current-top"><span className="eyebrow">LATEST SAVED FORECAST</span><StatusBadge label={w.source} tone="blue"/></div><div className="weather-current-main"><div><span className="weather-current-icon"><CloudSun size={54} strokeWidth={1.4}/></span><strong>{w.temperature}°<small>C</small></strong></div><span>Partly cloudy<small>Pedakakani, Guntur · updated {timeAgo(w.timestamp)}</small></span></div><div className="weather-current-stats"><div><Droplets size={18}/><span>Humidity</span><strong>{w.humidity}%</strong></div><div><CloudDrizzle size={18}/><span>Rainfall</span><strong>{w.rainfall_mm} mm</strong></div><div><Wind size={18}/><span>Wind</span><strong>{w.wind_kmh} km/h</strong></div><div><Cloud size={18}/><span>Rain chance</span><strong>{w.rain_probability}%</strong></div></div></section>
      <section className="surface weather-advice"><span className="advice-icon"><ThermometerSun size={22}/></span><p className="eyebrow">CROP + WEATHER INSIGHT</p><h2>{w.rain_probability>=65?'Rain may change your irrigation plan.':'A dry window for field checks.'}</h2><p>{w.rain_probability>=65?`Rain chance is ${w.rain_probability}%. If ${selected.name} soil is adequate, consider delaying irrigation. Check the local forecast first.`:`${selected.name} soil moisture is ${selected.sensor.soil_moisture.toFixed(1)}% and the saved rain chance is ${w.rain_probability}%. ${selected.irrigation.recommendation}.`}</p>
        <div className="weather-advice-bottom"><span>LOCAL RULE · NOT A FORECAST CERTAINTY</span><WhyButton onClick={()=>why(selected.id,'irrigation')}/></div></section></div>
    <section className="surface forecast-panel"><SectionHeading eyebrow="FOUR-DAY OUTLOOK" title="Look a little further." description={`Last saved ${timeAgo(w.timestamp)}. Offline? This forecast is cached, not live.`}/>
      <div className="forecast-grid">{w.forecast.map((day,i)=><div className="forecast-day" key={`${day.day}-${i}`}><span>{day.day}</span><span className="forecast-day-icon">{day.rain_probability>60?<CloudDrizzle size={30}/>:day.rain_probability>30?<CloudSun size={30}/>:<Sun size={30}/>}</span><strong>{day.temperature}°C</strong><small>{day.condition}</small><div className="forecast-rain"><Droplets size={14}/>{day.rain_probability}% chance</div></div>)}</div><div className="forecast-footer"><SourceNote>Forecast provider: {w.source} · not live data</SourceNote><span>Rain likelihood is a probability, not a guarantee.</span></div></section>
    <section className="surface field-weather-table"><SectionHeading eyebrow="SOIL × SKY" title="What it means for your fields." description="Local rules combine saved rain likelihood with each field's current soil reading."/>
      <div className="weather-field-list">{snapshot.fields.map(f=><button className="weather-field-row" key={f.id} onClick={()=>{selectField(f.id);navigate('irrigation');}}><span><strong>{f.name}</strong><small>{f.crop} · {f.growth.stage}</small></span><span>{f.sensor.soil_moisture.toFixed(1)}% <small>soil moisture</small></span><StatusBadge label={f.irrigation.needed?'Check irrigation':'Monitor'} tone={f.irrigation.needed?'amber':'green'}/><ArrowRight size={16}/></button>)}</div></section>
  </div>;
}
